export const GET_PRODUCTLIST_REQ='GET_PRODUCTLIST_REQ';
export const GET_PRODUCTLIST_SUCCESS='GET_PRODUCTLIST_SUCCESS';
export const GET_PRODUCTLIST_FAIL='GET_PRODUCTLIST_FAIL';

export const GET_SINGLEPRODUCT_REQ='GET_SINGLEPRODUCT_REQ';
export const GET_SINGLEPRODUCT_SUCCESS='GET_SINGLEPRODUCT_SUCCESS';
export const GET_SINGLEPRODUCT_FAIL='GET_SINGLEPRODUCT_FAIL';

export const GET_CART_ITEMS='GET_CART_ITEMS'
export const DELETE_CART_ITEM='DELETE_CART_ITEM'

export const USER_INFO_REQ='USER_INFO_REQ';
export const USER_INFO_SUCCESS='USER_INFO_SUCCESS';
export const USER_INFO_FAIL='USER_INFO_FAIL';

export const USER_LOGOUT='USER_LOGOUT';

export const USER_REGISTER_REQ='USER_REGISTER_REQ';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL';


export const UPDATE_USER_REQ='UPDATE_USER_REQ'
export const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL='UPDATE_USER_FAIL'

export const CART_SAVE_SHIPPING_ADDRESS='CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD='CART_SAVE_PAYMENT_METHOD'


